services:
  - type: worker
    name: telegram-bot-paid
    runtime: python
    plan: starter
    numInstances: 1
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DEPLOY_MODE
        value: polling
      - key: BOT_TOKEN
        sync: false
      - key: WEBSITE_URL
        sync: false
      - key: CUSTOMER_SERVICE_USERNAME
        sync: false
